"""add unique constraint for emp_dept

Revision ID: 485dc5edc8dd
Revises: b6556d45c13f
Create Date: 2026-05-31 13:54:33.185534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485dc5edc8dd'
down_revision: Union[str, Sequence[str], None] = 'b6556d45c13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_department', 'employee_department', ['employee_id', 'department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_department', 'employee_department', type_='unique')
    # ### end Alembic commands ###
