"""add experience, status

Revision ID: 68091ee584e2
Revises: 883989d383c2
Create Date: 2026-06-10 16:27:53.136616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import (
    postgresql,
)  # Imported for PostgreSQL-specific ENUM handling

# revision identifiers, used by Alembic.
revision: str = "68091ee584e2"
down_revision: Union[str, Sequence[str], None] = "883989d383c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Explicitly create the custom ENUM type in PostgreSQL first
    status_enum = postgresql.ENUM(
        "Active", "Inactive", "Probation", name="employeestatus"
    )
    status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column(
            "status",
            sa.Enum("Active", "Inactive", "Probation", name="employeestatus"),
            nullable=True,
        ),
    )
    op.add_column(
        "employees", sa.Column("experience", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "experience")
    op.drop_column("employees", "status")
    # ### end Alembic commands ###

    # 2. Explicitly drop the custom ENUM type from PostgreSQL after dropping the column
    status_enum = postgresql.ENUM(
        "Active", "Inactive", "Probation", name="employeestatus"
    )
    status_enum.drop(op.get_bind(), checkfirst=True)
