"""add role column to employee

Revision ID: 883989d383c2
Revises: 485dc5edc8dd
Create Date: 2026-06-01 14:14:02.433000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")
# revision identifiers, used by Alembic.
revision: str = "883989d383c2"
down_revision: Union[str, Sequence[str], None] = "485dc5edc8dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, server_default="Developer", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
