"""add junction table

Revision ID: b6556d45c13f
Revises: 0d1e7e9c044b
Create Date: 2026-05-31 10:24:09.901452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6556d45c13f'
down_revision: Union[str, Sequence[str], None] = '0d1e7e9c044b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_department',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department_department_id'), 'employee_department', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_department_employee_id'), 'employee_department', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_department_id'), 'employee_department', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_department_id'), table_name='employee_department')
    op.drop_index(op.f('ix_employee_department_employee_id'), table_name='employee_department')
    op.drop_index(op.f('ix_employee_department_department_id'), table_name='employee_department')
    op.drop_table('employee_department')
    # ### end Alembic commands ###
