"""addForeignKey

Revision ID: dce103e1bdfa
Revises: 8a00798c3d91
Create Date: 2026-05-28 17:29:59.765920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce103e1bdfa'
down_revision: Union[str, Sequence[str], None] = '8a00798c3d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_address_employee_id'), 'address', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'address', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_index(op.f('ix_address_employee_id'), table_name='address')
    op.drop_column('address', 'employee_id')
    # ### end Alembic commands ###
